# Generated by Django 4.2.7 on 2024-01-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='star',
            new_name='stars',
        ),
    ]
